### ISSUE TITLE
Encode UTC dates/times in place of Unix timestamps in filenames

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-app-jsonarchive#14]
The JSON archive files produced by this app are currently numbered using their creation time in seconds-since-epoch:

![image](https://user-images.githubusercontent.com/342712/166570323-1bb3af52-428e-46a7-a7ca-567ef9b7f083.png)

This makes it awkward to home in on a set of files likely to contain a particular event timestamp range by eye.

The current timestamp format was chosen because the colon `:` that appears in ISO-8601 date/time formatting is not allowed in filenames on Windows. This ticket proposes that we introduce a new formatting option "Format filenames with human-readable dates/times", which would produce filenames using ISO-8601 full formatting, but without `:`, resembling:

```
logs-2022-04-30T075301Z.json
```

(Changing the default formatting will be likely to break existing log shipping schemes, hence this isn't proposed as a new default.)

**Comment by liammclennan** [comment]
Done in https://www.nuget.org/packages/Seq.App.JsonArchive/1.0.42-dev
